### ISSUE TITLE
[cciss-vol-status] Please update to latest release 1.12

### ISSUE THREAD

**Issue by alexbarton** [eLvErDe/hwraid#84]
There is a newer version **1.12-1** of the "cciss-vol-status" package in Debian Sid & Buster ("testing") than this repository provides (**1.10**), but because of the _epoch_ used in versioning here, the package will actually be **downgraded** to **1:1.10-1hwraid1** …

It would be great if the cciss-vol-status package could be updated to version 1.12 here as well!

Homepage is http://cciss.sourceforge.net, download is available here: https://sourceforge.net/projects/cciss/files/cciss_vol_status/

For example, the P440ar controller which some servers are using here isn't supported/detected by the 1.10 version …

Thanks!
Alex

**Comment by geosone** [comment]
in my repo there is already an update 
apt-key adv --fetch-keys http://ftp.disconnected-by-peer.at/Repositories/go-hwraid/pubkey-aptly.asc
echo "deb http://ftp.disconnected-by-peer.at/Repositories/go-hwraid/ stretch main" > /etc/apt/sources.list.d/go-hwraid.list
apt-get update

**Comment by eLvErDe** [comment]
Hello,

I just updated the package to 1.12.

**Comment by jjakob** [comment]
I upgraded from xenial to focal and had to manually install the 1.12 package from official ubuntu repos:
```
~# apt-cache policy cciss-vol-status
cciss-vol-status:
  Installed: 1:1.10-1hwraid1
  Candidate: 1:1.10-1hwraid1
  Version table:
 *** 1:1.10-1hwraid1 100
        100 /var/lib/dpkg/status
     1.12-2 500
        500 http://apt-cacher.foo.bar:3141/ubuntu focal/universe amd64 Packages
```
(http://apt-cacher.foo.bar:3141/ is an internal mirror of the official ubuntu repo)
The package epoch `1:` is keeping the 1.12 version from getting installed, so I had to manually install it: `apt-get install cciss-vol-status=1.12-2` which worked.
Now I wonder what you use for the ID, in focal the card is using the `hpsa` driver and there is no /dev/cciss, maybe that was created by udev rules that now aren't present? The default ID `ID=/dev/cciss/c0d0` the script in `/etc/init.d/cciss-vol-statusd` uses obviously does not work. I can use /dev/disk/by-path/pci- if I always keep the card in the same slot. /dev/disk/by-id/scsi- or wwn- is another possibility, but those are tied to the array (logical volume) which may change if you delete or create arrays on the controller. /dev/sg0 may change across reboots so is not suitable. Right now I think using /dev/disk/by-path/pci- is the best option, and the package provided default should be modified, maybe by having the package provide udev rules to create persistent links to the card.

**Comment by jjakob** [comment]
Ubuntu's 1.12 package doesn't provide /etc/init.d/cciss-vol-statusd any more, but leaves it laying around from the old package version from hwraid repo. This doesn't work any more as they install the binary into /usr/bin, while the old init.d script looks for it in /usr/sbin. A possible workaround to continue using the old script is to modify it or put a symlink in /usr/sbin.

Change line 34:
```
-test -x /usr/sbin/cciss_vol_status || exit 0
+test -x /usr/bin/cciss_vol_status || exit 0
```

The provided /usr/share/doc/cciss-vol-status/examples/cron.daily-example is a lot more rudimentary and doesn't even work for hpsa, so it's not suitable.
So it would be nice if the init.d script were included in the debian package since it's a lot better than users trying to write something themselves.
Edit: I see Debian maintainers have refused to include the script https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=656630 so that settles that. Maybe they could be asked to reconsider since 10 years have passed since that decision.
